version: "3.6"
services:

  imixs-db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: workflow-db
    volumes: 
      - dbdata:/var/lib/postgresql/data
  
  imixs-app:
    image: imixs/imixs-process-manager
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://imixs-db/workflow-db"
    ports:
      - "8080:8080"
      - "8787:8787"
      - "9990:9990"
    volumes:
      - ./docker/deployments:/opt/jboss/wildfly/standalone/deployments/

#  imixsadmin:
#    image: imixs/imixs-admin
#    ports:
#      - "8888:8080"      
      
volumes:
  dbdata:   